### ISSUE TITLE
Bug with posts published today

### ISSUE THREAD

**Issue by Vayel** [IEMLdev/intlekt-importation#20]
Their date is the form of `Today, 3:08 PM`.

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/intlekt-importation/intlekt_importation/scoop.py", line 291, in scrap_url
    scrap_theme(theme)
  File "/home/ubuntu/intlekt-importation/intlekt_importation/scoop.py", line 308, in scrap_theme
    get_tagged_documents(tag, theme['title'], theme['posts'])
  File "/home/ubuntu/intlekt-importation/intlekt_importation/scoop.py", line 222, in get_tagged_documents
    date, title = get_date_title(meta, doc)
  File "/home/ubuntu/intlekt-importation/intlekt_importation/scoop.py", line 131, in get_date_title
    time_date = datetime.strptime(date, '%B %d, %I:%M %p')
  File "/usr/lib/python3.5/_strptime.py", line 510, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.5/_strptime.py", line 343, in _strptime
    (data_string, format))
ValueError: time data 'Today, 3:08 PM' does not match format '%B %d, %I:%M %p'
```

**Comment by PiggyGenius** [comment]
Fixed with 900a688a57e9ba805f3f0f37dedb97938d73f913.
